spring.application.name=api-estetica


# Configuraciones de JPA + MySQL
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Configuraciones de seguridad
spring.security.user.name=${SS_USER}
spring.security.user.password=${SS_PASSWORD}

#Configuración de JWT
security.jwt.private.key= ${PRIVATE_KEY}
security.jwt.user.generator=${USER_GENERATOR}

#Configuración Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=${DB_PLATFORM}
server.port =8080

